## Linear Algebra Task

In [1]:
!pip install pandas
!pip install matplotlib
!pip install seaborn
!pip install numpy

In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

### Task1 (Matrix Operations)

In [10]:
matA = np.array([[2,-1], [0,3]])
matB = np.array([[1,2], [-3,4]])
res1 = matA + matB
res2 = np.matmul(matA, matB)
res3 = 3 * matA - 2 * matB
print("A + B :\n", res1)
print("A * B :\n", res2) 
print("3A - 2B :\n", res3)

A + B :
 [[ 3  1]
 [-3  7]]
A * B :
 [[ 5  0]
 [-9 12]]
3A - 2B :
 [[ 4 -7]
 [ 6  1]]


### Task2 (Determinant and Inverse)

In [20]:
det=np.linalg.det(matA)
np.set_printoptions(formatter={'float': '{: 0.3f}'.format})
print("Determinant of A is:", det)
if det != 0:
    invA = np.linalg.inv(matA)
    print("A is invertible and its inverse is:\n", invA)
else:
    print("Matrix A is not invertible.")

Determinant of A is: 6.0
A is invertible and its inverse is:
 [[ 0.500  0.167]
 [ 0.000  0.333]]


### Task3 (Eigen Values and Eigen Vectors)

In [22]:
matC=np.array([[4,1], [-2,1]])
eigenvalues, eigenvectors = np.linalg.eig(matC)
print("Eigenvalues of C are:", eigenvalues)
print("Eigenvectors of C are:\n", eigenvectors)

Eigenvalues of C are: [ 3.000  2.000]
Eigenvectors of C are:
 [[ 0.707 -0.447]
 [-0.707  0.894]]


### Task4 (Solving Matrix)

In [32]:
car1 = np.array([4, 1.5, 100])
price_car1 = 20
car2 = np.array([6, 2.0, 150])
price_car2 = 30
car3 = np.array([8, 3.0, 200])


# Feature Matrix and Price Vector
mat = np.array([car1, car2])
pri = np.array([price_car1, price_car2])

car = np.dot((np.linalg.pinv(np.dot(mat.T, mat))), (np.dot(mat.T, pri)))

price_car3 = np.dot(car3.T, car)
print("Predicted price of car 3 is: ", round(price_car3, 2))

Predicted price of car 3 is:  40.0
